### ISSUE TITLE
Add breaking changes to plugin 10.2 version

### ISSUE THREAD

**Issue by sgelastic** [logstash-plugins/logstash-integration-kafka#45]
There was a change in 7.8 and specifically the Kafka plugin version 10.2, that changed the value for max_poll_records from string to number:
https://github.com/logstash-plugins/logstash-integration-kafka/blob/v10.2.0/CHANGELOG.md
https://github.com/logstash-plugins/logstash-integration-kafka/pull/30

This should be in Breaking Changes for docs, so users know that after upgrade this setting may break without update.

**Comment by yaauie** [comment]
@sgelastic can you provide an explicit example of a configuration that worked before but no longer works?

From what I can tell, the change brought forward _validation_ to be pre-startup, but did not otherwise change the behaviour of working configurations.

**Comment by jsermer** [comment]
I agree it definitely appears that way.  I found most settings that were changed from 'string' to 'number', that leaving them as strings still works.  However, max_poll_records does not seem to work the same way (even though the code looks like it should).

Setting the following:

```
max_poll_records => "500"
```

Results in an error:
```
{"level":"ERROR","loggerName":"logstash.agent","timeMillis":1623189362450,"thread":"Ruby-0-Thread-10@puma threadpool 001: :1","logEvent":{"message":"Internal API server error","status":500,"request_method":"GET","path_info":"/_node/stats/jvm","query_string":"","http_version":"HTTP/1.1","http_accept":null,"error":"Unexpected Internal Error","class":"LogStash::Instrument::MetricStore::MetricNotFound","message":"For path: events. Map keys: [:reloads]","backtrace":["/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:241:in `block in get_recursively'","org/jruby/RubyArray.java:1809:in `each'","/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'","/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:251:in `block in get_recursively'","org/jruby/RubyArray.java:1809:in `each'","/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'","/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:111:in `block in get'","org/jruby/ext/thread/Mutex.java:164:in `synchronize'","/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:110:in `get'","/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:124:in `get_shallow'","/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:173:in `block in extract_metrics'","org/jruby/RubyArray.java:1809:in `each'","org/jruby/RubyEnumerable.java:1126:in `inject'","/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:149:in `extract_metrics'","/usr/share/logstash/logstash-core/lib/logstash/api/service.rb:45:in `extract_metrics'","/usr/share/logstash/logstash-core/lib/logstash/api/commands/base.rb:37:in `extract_metrics'","/usr/share/logstash/logstash-core/lib/logstash/api/commands/stats.rb:73:in `events'","/usr/share/logstash/logstash-core/lib/logstash/api/modules/node_stats.rb:57:in `events_payload'","/usr/share/logstash/logstash-core/lib/logstash/api/modules/node_stats.rb:37:in `block in GET /?:filter?'","org/jruby/RubyMethod.java:131:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'","org/jruby/RubyKernel.java:1189:in `catch'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'","org/jruby/RubyArray.java:1809:in `each'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'","org/jruby/RubyKernel.java:1189:in `catch'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'","org/jruby/RubyKernel.java:1189:in `catch'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'","org/jruby/RubyArray.java:1809:in `each'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'","/usr/share/logstash/logstash-core/lib/logstash/api/rack_app.rb:74:in `call'","/usr/share/logstash/logstash-core/lib/logstash/api/rack_app.rb:48:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:718:in `handle_request'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:472:in `process_client'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:328:in `block in run'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/thread_pool.rb:134:in `block in spawn_thread'"]}}
```

Setting it as follows allows logstash to bring the pipeline up properly:

```
max_poll_records => 500
```

I have tested other options leaving them as strings w/o issue.  I'll be sure to correct my option types after I complete the upgrade from 7.6 to 7.13 across my fleet, but just wanted to mention that leaving max_poll_records as a string appears to be a breaking change for some reason.

```
consumer_threads
session_timeout_ms
max_partition_fetch_bytes
```

**Comment by yaauie** [comment]
Absent follow-up indicating what the reported breaking changes were, I am going to close this issue.

As mentioned above, the linked PR brought validation forward, but was done so in a way that was NOT breaking. Previously-valid configurations will continue to work without modification, and previously-invalid configurations will merely error _sooner_ and _more clearly_ when it is safer to do so (in the Output's case, this prevents a data-loss scenario).
